fruits = [] #empty list 
print(fruits)
fruits.append("mango")
fruits.append("banana")
fruits.append("pinapple")
fruits.append("apple")
fruits.append("cherry")
print(fruits)
fruits.insert(0,'kiwi')
fruits.insert(2,'apple')
print(fruits)
count = fruits.count("apple")
print(f"apple = {count}")
vegis = ['potato','onion','tomato']
print(vegis)
fruits.extend(vegis)
print(fruits)
vegis.remove("potato")
print(vegis)
value = vegis.pop()
print(f"removed value = {value}")
vegis.clear()
print(vegis)
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)
fruits2 = fruits
print(fruits)
print(fruits2)
fruits.pop()
fruits2.pop()
print(fruits)
print(fruits2)
copy_fruits = fruits.copy() #will actaully copy fruits into copy_fruits 
copy_fruits.clear()
print(copy_fruits)
print(fruits)